[2025-07-16T22:04:58.641+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-16T22:04:58.722+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_to_postgres.load_csv_to_postgres scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-16T22:04:58.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_to_postgres.load_csv_to_postgres scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-16T22:04:58.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-16T22:04:58.765+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-07-16 00:00:00+00:00
[2025-07-16T22:04:58.780+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_to_postgres', 'load_csv_to_postgres', 'scheduled__2025-07-16T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/load_to_postges_dag.py', '--cfg-path', '/tmp/tmpb45htnsi']
[2025-07-16T22:04:58.785+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask load_csv_to_postgres
[2025-07-16T22:04:58.786+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T22:04:58.787+0000] {standard_task_runner.py:63} INFO - Started process 319 to run task
[2025-07-16T22:04:58.864+0000] {task_command.py:426} INFO - Running <TaskInstance: load_to_postgres.load_csv_to_postgres scheduled__2025-07-16T00:00:00+00:00 [running]> on host b72193923242
[2025-07-16T22:04:59.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T00:00:00+00:00'
[2025-07-16T22:04:59.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-16T22:04:59.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-16T22:04:59.290+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_to_postges_dag.py", line 14, in load_csv_to_postgres
    df = pd.read_csv('data/enriched_jobs.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/enriched_jobs.csv'
[2025-07-16T22:04:59.314+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_to_postgres, task_id=load_csv_to_postgres, run_id=scheduled__2025-07-16T00:00:00+00:00, execution_date=20250716T000000, start_date=20250716T220458, end_date=20250716T220459
[2025-07-16T22:04:59.345+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task load_csv_to_postgres ([Errno 2] No such file or directory: 'data/enriched_jobs.csv'; 319)
[2025-07-16T22:04:59.406+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-16T22:04:59.430+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T22:04:59.436+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-16T22:18:12.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-16T22:18:12.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_to_postgres.load_csv_to_postgres scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-16T22:18:12.526+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_to_postgres.load_csv_to_postgres scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-16T22:18:12.527+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-16T22:18:12.552+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-07-16 00:00:00+00:00
[2025-07-16T22:18:12.569+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_to_postgres', 'load_csv_to_postgres', 'scheduled__2025-07-16T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/load_to_postges_dag.py', '--cfg-path', '/tmp/tmpatxeqfhu']
[2025-07-16T22:18:12.572+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask load_csv_to_postgres
[2025-07-16T22:18:12.575+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T22:18:12.576+0000] {standard_task_runner.py:63} INFO - Started process 178 to run task
[2025-07-16T22:18:12.643+0000] {task_command.py:426} INFO - Running <TaskInstance: load_to_postgres.load_csv_to_postgres scheduled__2025-07-16T00:00:00+00:00 [running]> on host 0e8814527962
[2025-07-16T22:18:13.019+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_to_postgres' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T00:00:00+00:00'
[2025-07-16T22:18:13.022+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-16T22:18:13.063+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-16T22:18:13.064+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_to_postges_dag.py", line 14, in load_csv_to_postgres
    df = pd.read_csv('/opt/airflow/data/enriched_jobs.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/enriched_jobs.csv'
[2025-07-16T22:18:13.091+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=load_to_postgres, task_id=load_csv_to_postgres, run_id=scheduled__2025-07-16T00:00:00+00:00, execution_date=20250716T000000, start_date=20250716T221812, end_date=20250716T221813
[2025-07-16T22:18:13.123+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task load_csv_to_postgres ([Errno 2] No such file or directory: '/opt/airflow/data/enriched_jobs.csv'; 178)
[2025-07-16T22:18:13.157+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-16T22:18:13.183+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T22:18:13.187+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
